# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev

# Set work directory
WORKDIR /app

# Copy project files
COPY . /app

# Upgrade pip and install dependencies
RUN pip install --upgrade pip \
    && pip install beautifulsoup4 httpx 'mcp[cli]>=1.5.0' python-dotenv

# Expose port if needed (MCP runs via stdio, so not mandatory)

# Command to run the MCP server
CMD ["python", "main.py"]
